### ISSUE TITLE
Persist datetime values as integers

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian-core#2]
Based on cursory testing for the database (pun intentional) from Librarian v0.4, it is determined that the database column containing timestamps as `TEXT` value poses a considerable performance hit when usde in queries like `ORDER BY`. Consider switching to storage in `INTEGER` format using seconds from Unix epoch.

**Comment by integricho** [comment]
Solved in fc3eed60ccfc324170de6d13c9729dd2145bd0d1
