### ISSUE TITLE
Developer Docs

### ISSUE THREAD

**Issue by dbinoj** [Outernet-Project/librarian-core#9]
Is there any developer documentation available?
From skimming thru the source code, I find that this is a web project and you are using Bottle Framework. I also could not find any info here in github on the project's purpose in the outernet ecosystem. Is there some info else where that I've missed looking?

**Comment by foxbunny** [comment]
We currently don't have developer documentation. Librarian is web-based interface for Outernet receivers. It has recently been split into about a dozen odd packages that provide different functionality that was previously part of [Librarian app](https://github.com/Outernet-Project/librarian/). `librarian-core` is a low-level package that provides server management, task queue, ACL, and a few other pieces that all other components rely on.

**Comment by dbinoj** [comment]
A list of such sub packages and an one line description will give clarity to developers looking at outernet's code for the first time. Shall I create a list in this project's README file for a start?

**Comment by foxbunny** [comment]
We will publish documentation once we release the new software.

**Comment by dbinoj** [comment]
Oh. Okay. I thought maybe other volunteer devs could also contribute *while* the software is being built! Community can reduce the development time for outernet team by at least trying to fix issues. 
BTW, what you guys do is really great and thought could lend a hand :smile:

**Comment by foxbunny** [comment]
Sure, feel free to submit a pull request. You can see a list of packages that are part of a receiver build [here](https://github.com/Outernet-Project/orx-rpi/tree/feature/ngfm/rpi/package). If you have any more questions, feel free to continue the discussion here or in the [forums](https://discuss.outernet.is/). Closing this issue for now.
